name: rainwater_harvesting_app
description: RTRWH Flutter client
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.10.0
  firebase_auth: ^4.6.0
  cloud_firestore: ^5.2.0
  flutter_map: ^4.0.0
  latlong2: ^0.9.0
  http: ^0.14.0
  provider: ^6.0.5
  geolocator: ^9.0.2
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
